version: '3'
services:
  app:
    image: node:latest
    ports:
      - 3334:3334
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    entrypoint: yarn docker
  # database:
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: wrgs2703
  #     MYSQL_USER: wargas
  #     MYSQL_PASSWORD: wrgs2703
